### ISSUE TITLE
No results below search prompt - Failure to find file with spaces in name (rg)

### ISSUE THREAD

**Issue by sjsepan3** [clearfeld/vscode-search-replace-inplace-commands#1] opened 2023-01-08 18:31 UTC
Very nice looking concept; cannot quite get it to work on my vscode. Maybe I am missing another dependency...?
I have screenshots (if I can figure out how to post them), showing that ripgrep is installed and working.

Expected Behavior:
typing text at 'Go to line:' prompt will display result below

Actual Behavior:
no results below

Steps taken:
-install extension
-install ripgrep through package manager, and test in terminal with text file
-activate extension in vscode and type at prompt

VSCODE:
Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:27:19.253Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-57-generic
Sandboxed: No

System Info:
System:
  Kernel: 5.15.0-57-generic x86_64 bits: 64 compiler: gcc v: 11.3.0 Desktop: Cinnamon 5.6.5
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: Dell product: OptiPlex 7020 v: 00 serial: <superuser required> Chassis:
    type: 6 serial: <superuser required>
  Mobo: Dell model: 0F5C5X v: A00 serial: <superuser required> BIOS: Dell v: A10
    date: 09/22/2016
Battery:
  Device-1: hidpp_battery_0 model: Logitech M570 serial: <filter> charge: 25% status: Discharging
CPU:
  Info: quad core model: Intel Core i5-4590 bits: 64 type: MCP arch: Haswell rev: 3 cache:
    L1: 256 KiB L2: 1024 KiB L3: 6 MiB
  Speed (MHz): avg: 1210 high: 1250 min/max: 800/3700 cores: 1: 1250 2: 1197 3: 1197 4: 1197
    bogomips: 26337
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: AMD Oland [Radeon HD 8570 / R5 430 OEM R7 240/340 Radeon 520 OEM] vendor: Dell
    driver: radeon v: kernel pcie: speed: 8 GT/s lanes: 8 ports: active: DVI-I-1 empty: DP-1
    bus-ID: 01:00.0 chip-ID: 1002:6611
  Device-2: Realtek RTL2838 DVB-T type: USB driver: dvb_usb_rtl28xxu,rtl2832_sdr bus-ID: 3-8:4
    chip-ID: 0bda:2838
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: ati,radeon
    unloaded: fbdev,modesetting,vesa gpu: radeon display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: DVI-0 mapped: DVI-I-1 model: Acer H233H res: 1920x1080 dpi: 96 diag: 585mm (23")
  OpenGL: renderer: AMD OLAND (LLVM 13.0.1 DRM 2.50 5.15.0-57-generic) v: 4.5 Mesa 22.0.5
    direct render: Yes
Audio:
  Device-1: Intel 8 Series/C220 Series High Definition Audio vendor: Dell driver: snd_hda_intel
    v: kernel bus-ID: 00:1b.0 chip-ID: 8086:8c20
  Device-2: AMD Oland/Hainan/Cape Verde/Pitcairn HDMI Audio [Radeon HD 7000 Series] vendor: Dell
    driver: snd_hda_intel v: kernel pcie: speed: 8 GT/s lanes: 8 bus-ID: 01:00.1 chip-ID: 1002:aab0
  Sound Server-1: ALSA v: k5.15.0-57-generic running: yes
  Sound Server-2: JACK v: 1.9.20 running: no
  Sound Server-3: PulseAudio v: 15.99.1 running: yes
  Sound Server-4: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Ethernet I217-LM vendor: Dell driver: e1000e v: kernel port: f040
    bus-ID: 00:19.0 chip-ID: 8086:153a
  IF: eno1 state: up speed: 1000 Mbps duplex: full mac: <filter>
  IF-ID-1: virbr0 state: down mac: <filter>
Drives:
  Local Storage: total: 1.93 TiB used: 1.9 TiB (98.3%)
  ID-1: /dev/sda vendor: Western Digital model: WDS100T2B0A-00SM50 size: 931.51 GiB
    speed: 6.0 Gb/s serial: <filter>
  ID-2: /dev/sdb vendor: Samsung model: SSD 840 EVO 120GB size: 111.79 GiB speed: 6.0 Gb/s
    serial: <filter>
  ID-3: /dev/sdc type: USB vendor: Western Digital model: WD My Passport 25E1 size: 931.48 GiB
    serial: <filter>
Partition:
  ID-1: / size: 98.44 GiB used: 28.68 GiB (29.1%) fs: ext4 dev: /dev/sdb1
  ID-2: /home size: 915.82 GiB used: 728.99 GiB (79.6%) fs: ext4 dev: /dev/sda1
Swap:
  ID-1: swap-1 type: partition size: 11.21 GiB used: 1.2 MiB (0.0%) priority: -2 dev: /dev/sdb2
Sensors:
  System Temperatures: cpu: 29.8 C mobo: 27.8 C gpu: radeon temp: 36.0 C
  Fan Speeds (RPM): N/A
Repos:
  Packages: note: see --pkg apt: 3961
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/docker.list
    1: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https: //download.docker.com/linux/ubuntu vanessa stable
  Active apt repos in: /etc/apt/sources.list.d/gambas-team-gambas3-jammy.list
    1: deb http: //ppa.launchpad.net/gambas-team/gambas3/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/jonaski-strawberry-jammy.list
    1: deb http: //ppa.launchpad.net/jonaski/strawberry/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/microsoft-prod.list
    1: deb [arch=amd64,arm64,armhf] https: //packages.microsoft.com/ubuntu/22.04/prod jammy main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com vera main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/vscode.list
    1: deb [arch=amd64,arm64,armhf] http: //packages.microsoft.com/repos/code stable main
  Active apt repos in: /etc/apt/sources.list.d/wavebox-stable.list
    1: deb [arch=amd64] https: //download.wavebox.app/stable/linux/deb/ amd64/
Info:
  Processes: 288 Uptime: 7h 12m Memory: 10.65 GiB used: 6.08 GiB (57.1%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.3.0 alt: 11 Client: Unknown python client inxi: 3.3.13

**Comment by sjsepan3** [comment] 2023-01-08 18:32
shot of ripgrep running in bash

![scr0](https://user-images.githubusercontent.com/121126599/211212775-c60c7e16-e64f-4b5d-b3e4-3dc4fb1e3c7e.png)

**Comment by sjsepan3** [comment] 2023-01-08 18:33
shot of ripgrep running in vscode integrated terminal, with test file content open above

![scr1](https://user-images.githubusercontent.com/121126599/211212801-4d865380-9c01-466f-9a16-b56d3c17c90a.png)

**Comment by sjsepan3** [comment] 2023-01-08 18:34
shot of the extension running and search prompt filled, but no key-press seems to activate search, and no results appear while typing

![scr2](https://user-images.githubusercontent.com/121126599/211212877-c98325b9-d9df-421b-b078-1d3a2d9039d5.png)

**Comment by sjsepan3** [comment] 2023-01-08 18:37
behavior is the same in Codium, also.

To be fair, I have a fair # of extensions running, and I'm going to look into starting up Extension Bisect to see if I can determine which, if any, might be causing interference...
UPDATE: Bisect did not seem to narrow the problem down to a combination with any other extensions.

**Comment by clearfeld** [comment] 2023-01-08 20:55
Everything in regards to your setup and install seems correct. I've done a bit of testing and I've noticed that the search results from ripgrep (rg) won't show when a file hasn't been saved. Which makes sense, since currently I'm invoking ripgrep in a child process pointing to the file on disk. 

Could you confirm if you see results after you save the file? If that's the case I'll rename the ticket to better reflect the issue. 

I'm going to modify this command to work with the editor contents regardless if they're saved to disk or not. That way the behavior should be closer to what is expected.

**Comment by sjsepan3** [comment] 2023-01-08 21:42
Yes; the screenshots of the test data were of an already-saved file, named 'this is a test' (no extension). Put another way, the file used to test 'rg' from the command line was the same one opened in vscode.

Steve

**Comment by clearfeld** [comment] 2023-01-08 21:56
I've confirmed the issue, seems like the cmd string I was sending to the child process didn't have surrounding quotes for the filename resulting in the failure. I've fixed the issue and I've deployed an update to the extension. 

I'm going to open a separate issue for the failure to search none saved file contents in the active editor.

**Comment by sjsepan3** [comment] 2023-01-08 22:10
My vscode picked up the update to v0.0.2 right away, but so far nothing is happening. I even restarted it after the update. 
I may have to try disabling the other extensions anyway, despite the Extension Bisect results.

**Comment by clearfeld** [comment] 2023-01-08 22:25
In that case could you try running the command `Developer: Toggle Developer Tools` default shortcut `Ctrl + Shift + I`, and paste any errors or screenshot of the output that has something along the lines of `... Error: command failed: rg ...` inside. Whatever the issue is, it seems to be tied to the invoking of ripgrep in the child process.

**Comment by sjsepan3** [comment] 2023-01-08 22:49
OK, now we're getting somewhere...I saved the output from the troubleshooting mode Console to a .log file.
But the gist of it seems to be that the command doesn't like my extensionless filename. I am going to try it WITH a filename and see if it behaves differently...

[vscode-app-1673217994696.log](https://github.com/clearfeld/vscode-search-replace-inplace-commands/files/10369680/vscode-app-1673217994696.log)

**Comment by sjsepan3** [comment] 2023-01-08 22:53
No, same message in the log

[vscode-app-1673218290283.log](https://github.com/clearfeld/vscode-search-replace-inplace-commands/files/10369682/vscode-app-1673218290283.log)

**Comment by sjsepan3** [comment] 2023-01-08 22:55
I tried it out in the console, and it became obvious...

rg "test" "home/sjsepan/this is a test.txt" --json -i

home/sjsepan/this is a test.txt: No such file or directory (os error 2)
{"data":{"elapsed_total":{"human":"0.001279s","nanos":1279349,"secs":0},"stats":{"bytes_printed":0,"bytes_searched":0,"elapsed":{"human":"0.000000s","nanos":0,"secs":0},"matched_lines":0,"matches":0,"searches":0,"searches_with_match":0}},"type":"summary"}

home is wanting to be an absolute path, but without '/', so our relative location is from '~' AKA /home/sjsepan

**Comment by sjsepan3** [comment] 2023-01-08 22:58
I will have to change the filename back to extension-less and re-test, but I'll wait till we clear this first...

**Comment by clearfeld** [comment] 2023-01-08 23:13
I believe I found the issue I was using `editor.document.uri.path` instead of `fsPath`, which was resulting in none absolute path names. The change has been made and extension `v0.0.4` has been deployed, hopefully that fully resolves this issue.

**Comment by sjsepan3** [comment] 2023-01-08 23:26
re-testing...
working with '.txt' extension
!working without extension; checking log...

log said ext thought it was still dealing with file having extension when I had made another file 'this is a test2' (no extension) and both files ere open, with new one active; when I closed search and re-opened, it worked. will re-create and write up more clearly (later tonight)

**Comment by sjsepan3** [comment] 2023-01-09 01:52
OK, loaded v0.0.4, and re-tested: working
changing the take/file in the middle works as expected.

I found an un-related issue that I am going to submit, but I have nothing more for this one. Thanks!

**Comment by clearfeld** [comment] 2023-01-09 02:40
No problem, glad we were able to resolve this. Closing this issue since its confirmed to be resolved.

**Closed as completed by clearfeld** 2023-01-09 02:40 UTC
Labels: bug
